apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-csi-multi-attach
parameters:
  type: multi-attach
provisioner: cinder.csi.openstack.org
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true