apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-file-storage
  namespace: mattermost
spec:
  storageClassName: cinder-csi-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi