apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost-installation
  namespace: mattermost
spec:
  image: registry.local/mattermost/mattermost-enterprise-edition
  version: release-8.0
  imagePullSecrets:
    - name: registry-local-client
  licenseSecret: ""
  size: 100users
  replicas: 1  # One and only one replica is mandatory as block storage volume is used for file storage
  ingress:
    enabled: true
    host: mattermost.andennis.com
    annotations:
      kubernetes.io/ingress.class: nginx
    tlsSecret: "mattermost.andennis.com-tls"
  podTemplate:
    securityContext:
      fsGroup: 2000  #user/group - mattermost
  database:
    external:
      secret: mattermost-db
  fileStore:
    externalVolume:
      volumeClaimName: mattermost-file-storage
