apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: default
spec:
  storageClassName: cinder-csi-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi