apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-csi-retain
provisioner: cinder.csi.openstack.org
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true