apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: web-ping-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      project: web-ping
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        project: web-ping
    spec:
      containers:
      - name: web-ping-pod
        image: registry.local/web-ping:1.3.2
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: registry-local-client