apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: web-app1-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      project: web-app1
  template:
    metadata:
      labels:
        project: web-app1
    spec:
      containers:
      - name: web-app1-pod
        image: andennis/web-app1
        ports:
        - containerPort: 5000
