apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: web-ping-pod
  labels:
    project: web-ping
spec:
  containers:
    - name: web-ping
      image: andennis/web-ping:1.1
#      image: 192.168.2.29/web-ping:1.1
      ports:
        - containerPort: 5000
#  imagePullSecrets:
#    - name: docker-pull-secret