apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: web-app1-pod
  labels:
    project: web-app1
spec:
  containers:
    - name: web-ctr
      image: andennis/web_app1
      ports:
        - containerPort: 5000