apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: web-ping-pod
  labels:
    project: web-ping
spec:
  containers:
    - name: web-ctr
      image: andennis/web-ping:1.0
      ports:
        - containerPort: 5000