apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: web-app1-lb
spec:
  type: LoadBalancer
  externalIPs:
    - 192.168.2.101
  ports:
  - port: 8080
    targetPort: 5000
  selector:
    project: web-app1