apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: temp-test-net
spec:
  containers:
  - name: ubuntu
    image: weibeld/ubuntu-networking:latest
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]