apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-local
  namespace: kube-system
  labels:
    app: registry-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-local
  template:
    metadata:
      labels:
        app: registry-local
    spec:
      containers:
      - name: registry-local
        image: registry:2.8.2
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: repo-vol
          mountPath: "/var/lib/registry"
        - name: certs-vol
          mountPath: "/certs"
          readOnly: true
        - name: auth-vol
          mountPath: "/auth"
          readOnly: true
        env:
        - name: REGISTRY_AUTH
          value: "htpasswd"
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry Realm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: "/auth/htpasswd"
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: "/certs/tls.crt"
        - name: REGISTRY_HTTP_TLS_KEY
          value: "/certs/tls.key"
      volumes:
      - name: repo-vol
        persistentVolumeClaim:
          claimName: registry-pvc
      - name: certs-vol
        secret:
          secretName: registry-local-tls
      - name: auth-vol
        secret:
          secretName: registry-local-auth
