apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: default
spec:
  selector:
   matchLabels:
    app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin4
          image: registry.local/pgadmin4:7.4
          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
          env:
           - name: PGADMIN_DEFAULT_EMAIL
             value: "admin@andennis.com"
           - name: PGADMIN_DEFAULT_PASSWORD
             value: admin
           - name: PGADMIN_PORT
             value: "80"
          ports:
            - containerPort: 80
      securityContext:
        fsGroup: 5050
#      initContainers:
#        - name: pgadmin-permission-fix
#          image: alpine
#          args: [ "sh", "-c", "chown 5050:5050 /var/lib/pgadmin " ]
#          volumeMounts:
#            - name: pgadmin-data
#              mountPath: /var/lib/pgadmin
      imagePullSecrets:
        - name: registry-local-client
      volumes:
        - name: pgadmin-data
          persistentVolumeClaim:
            claimName: pgadmin
